language: node_js
node_js:
  - 13

services:
  - docker

#Pre-testing installs
install:
  - echo "nothing to be installed"

#Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node-new .
  - docker tag simple-node-new amusanga/simple-node-new:latest

#Tasks to perform after the process is successful. Formatting the docker usrname and password as below enables you to programmatically login without having to expose the password in the logs.

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push amusanga/simple-node-new